backend:
  name: github
  repo: goulette-coder/legrandvert-site
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Site"
    files:
      - label: "Contenu principal"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "À propos", name: "about", widget: "text" }
          - { label: "Facebook", name: "facebook", widget: "string", required: false }
          - { label: "Instagram", name: "instagram", widget: "string", required: false }
          - { label: "Google Review", name: "google_review", widget: "string", required: false }
